'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type Product = { _id: string; title?: string; name?: string; description?: string; benefits?: string; category?: string; price?: number; offerPrice?: number; stock?: number; images?: Array<{ url?: string }>; care?: { height?: string; potSize?: string; watering?: string; sunlight?: string }; seller?: { name?: string; sellerProfile?: { shopName?: string } } };
const apiUrl = `${(process.env.NEXT_PUBLIC_LEGACY_API_URL || 'https://gaurav-nursery.onrender.com').replace(/\/$/, '')}/api`;
const getToken = () => window.localStorage.getItem('gaurav_nursery_token') || window.sessionStorage.getItem('gaurav_nursery_token');

export default function ProductDetails() {
  const { id } = useParams<{ id: string }>();
  const [product, setProduct] = useState<Product | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${apiUrl}/products/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data?.message); setProduct(data.product); }).catch(() => setMessage('This product is unavailable or could not be loaded.')).finally(() => setLoading(false)); }, [id]);
  async function addToCart() { const token = getToken(); if (!token) { window.location.assign('/login'); return; } const response = await fetch(`${apiUrl}/cart`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ productId: product?._id, quantity: 1 }) }); setMessage(response.ok ? 'Added to your cart.' : 'Could not add this product to the cart.'); }
  if (loading) return <main className="loading-page">Loading product…</main>;
  if (!product) return <main className="loading-page"><h2>Product not found</h2><a className="button" href="/shop">Browse plants</a></main>;
  const price = Number(product.offerPrice || product.price || 0);
  return <main><div className="offerbar">Free delivery on orders above ₹499 <span>•</span> Healthy plant guarantee</div><nav><a className="logo" href="/"><b>✦</b><span>Gaurav Nursery<small>Trusted Plant Studio</small></span></a><div className="quick"><a href="/shop">Shop</a><a href="/wishlist">Wishlist</a><a href="/cart">Cart</a></div></nav><div className="product-detail"><section className="detail-image">{product.images?.[0]?.url ? <img src={product.images[0].url} alt={product.title || product.name || 'Plant'} /> : <span>🌿</span>}</section><section className="detail-info"><p className="eyebrow">{product.category || 'NURSERY PLANT'}</p><h1>{product.title || product.name}</h1><p className="detail-price">₹{price.toLocaleString('en-IN')}</p><p>{product.description || 'Healthy nursery-grown plant, packed with care for safe delivery.'}</p>{product.benefits && <p><b>Benefits:</b> {product.benefits}</p>}<p className={product.stock ? 'in-stock' : 'out-stock'}>{product.stock ? `${product.stock} available` : 'Out of stock'}</p><button className="button" disabled={!product.stock} onClick={addToCart}>{product.stock ? 'Add to cart' : 'Out of stock'}</button>{message && <p className="store-message">{message}</p>}<p className="seller-name">Sold by {product.seller?.sellerProfile?.shopName || product.seller?.name || 'Gaurav Nursery'}</p></section></div><section className="care-grid"><h2>Plant care guide</h2><div><article><b>Plant size</b><p>{product.care?.height || 'As shown in product images'}</p></article><article><b>Pot size</b><p>{product.care?.potSize || 'Nursery pot included'}</p></article><article><b>Watering</b><p>{product.care?.watering || 'Water when top soil feels dry'}</p></article><article><b>Sunlight</b><p>{product.care?.sunlight || 'Bright indirect light'}</p></article></div></section></main>;
}
