'use client';

import { FormEvent, useEffect, useState } from 'react';

type Product = { _id: string; title?: string; name?: string; description?: string; category?: string; price?: number; offerPrice?: number; stock?: number; images?: Array<{ url?: string }> };
const apiUrl = `${(process.env.NEXT_PUBLIC_LEGACY_API_URL || 'https://gaurav-nursery.onrender.com').replace(/\/$/, '')}/api`;
const getToken = () => window.localStorage.getItem('gaurav_nursery_token') || window.sessionStorage.getItem('gaurav_nursery_token');

export default function ShopPage() {
  const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function load(search = '') { setLoading(true); try { const response = await fetch(`${apiUrl}/products?limit=24${search ? `&search=${encodeURIComponent(search)}` : ''}`); const data = await response.json(); if (!response.ok) throw new Error(data?.message); setProducts(data.products || []); } catch { setMessage('Unable to load plants right now. Please refresh in a moment.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function search(event: FormEvent) { event.preventDefault(); load(query); }
  async function add(productId: string) { const token = getToken(); if (!token) { window.location.assign('/login'); return; } try { const response = await fetch(`${apiUrl}/cart`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ productId, quantity: 1 }) }); if (!response.ok) throw new Error(); setMessage('Added to cart.'); } catch { setMessage('Could not add product to cart.'); } }
  return <main><div className="offerbar">Free delivery on orders above ₹499 <span>•</span> Secure payments</div><nav><a className="logo" href="/"><b>✦</b><span>Gaurav Nursery<small>Trusted Plant Studio</small></span></a><form className="search" onSubmit={search}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search plants, pots, seeds and more" /><button>Search</button></form><div className="quick"><a href="/wishlist">Wishlist</a><a href="/cart">Cart</a><a href="/login">Login</a></div></nav><div className="menu"><a className="menuall" href="/categories">All Categories</a><a href="/offers">Offers</a><a href="/blog">Blog</a></div><div className="section-title"><div><p className="eyebrow">SHOP HEALTHY PLANTS</p><h2>All Plants</h2></div><p>{products.length} products found</p></div>{message && <p className="store-message">{message}</p>}<div className="shop-layout"><aside className="filters"><h3>Filters</h3><b>Categories</b>{['Indoor Plants', 'Outdoor Plants', 'Flowering Plants', 'Air Purifying Plants', 'Seeds'].map((category) => <button key={category} onClick={() => load(category)}>{category}</button>)}<button onClick={() => load()}>Clear filters</button></aside><section className="product-grid">{loading && Array.from({ length: 8 }).map((_, index) => <article className="product-tile product-loading" key={index} />)}{!loading && products.map((product) => <article className="product-tile" key={product._id}><a href={`/products/${product._id}`}>{product.images?.[0]?.url ? <img src={product.images[0].url} alt={product.title || product.name || 'Plant'} /> : <span>🌿</span>}<p>{product.category || 'Nursery plant'}</p><h3>{product.title || product.name}</h3></a><b>₹{Number(product.offerPrice || product.price || 0).toLocaleString('en-IN')}</b><button className="button" disabled={!product.stock} onClick={() => add(product._id)}>{product.stock ? 'Add to cart' : 'Out of stock'}</button></article>)}</section></div></main>;
}
