const labels: Record<string, string> = { users: 'Customer Management', sellers: 'Seller Management', products: 'Product Management', categories: 'Categories Management', orders: 'Orders Management', payments: 'Payments & Payouts', refunds: 'Refunds & Returns', coupons: 'Coupons & Offers', banners: 'CMS · Banners', reports: 'Reports & Analytics', settings: 'System Settings', analytics: 'Marketplace Analytics', staff: 'Staff & Permissions' };
const menu = ['Dashboard', 'Users', 'Sellers', 'Products', 'Categories', 'Orders', 'Payments', 'Payouts', 'Coupons', 'Blogs', 'Banners', 'Reports', 'Settings', 'Activity Logs'];

export default async function AdminScreen({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const section = slug[0] ?? 'dashboard';
  const title = labels[section] ?? section.replaceAll('-', ' ');
  return <main className="shell"><aside><div className="brand"><b>✦</b><span>Gaurav Nursery<small>Admin Panel</small></span></div><nav>{menu.map((item,index) => <a href="#" key={item}><i>{['⌂','♙','▣','□','◫','▤','₹','◉','%','▤','▱','◌','⚙','◷'][index]}</i>{item}</a>)}<a className="logout" href="#">↪ Logout</a></nav></aside><section className="content"><header><div><p>Marketplace control centre</p><h1>{title}</h1></div><div className="header-tools">⌕　♧　<span>GN</span></div></header><div className="stats">{[['Pending Approval','38','+12%'],['Open Orders','126','+8%'],['Active Sellers','48','+10%'],['Revenue','₹8,75,230','+10%']].map(([label,value,change]) => <article key={label}><p>{label}</p><h2>{value}</h2><b>{change}</b></article>)}</div><article className="recent"><div className="panel-title"><div><h3>{title} queue</h3><p>Review, filter and manage marketplace records.</p></div><button>Export report</button></div>{['Green Leaf Nursery', 'Areca Palm Plant', 'Order #GN10042', 'Bloom Garden Store', 'Snake Plant Premium'].map((item,index) => <div className="order" key={item}><span><b>{item}</b></span><b>{['Seller','Product','Order','Seller','Product'][index]}</b><em className={index < 2 ? 'pending' : 'delivered'}>{index < 2 ? 'Pending review' : 'Active'}</em></div>)}</article></section></main>;
}
